### ISSUE TITLE
the tag .form__input:not(:focus) didn't work.

### ISSUE THREAD

**Issue by soutovnc** [bedimcode/login-form-input-google#1]
Hello, I tried to implement your form style guide. But, it didn't work properly.
I suggest changing in .scss:

`
.form_input:not(:placeholder-shown).form_input:not(:focus) + .form_label {
        top: 1rem;
        left: .8rem;
        z-index: 10;
        font-size: 1rem;
        font-weight: 500;
      }
`

**Comment by bedimcode** [comment]
It is the same only that the letters are larger and do not remain positioned at the top, the top property must have a negative number
